### PR TITLE
To-do List app

### PR DESCRIPTION
**Pull request by Trictonicmp**
# Application additions
In this PR I:
- Added HTML skeleton of the page
- Added styles to make it look like the one in the requirements 
- Added functionality to the form to add tasks
- Added functionality to be able to edit a task
- Added functionality to delete a selected task
- Added functionality to delete tasks marked as done
- Added functionality to animate new tasks and deleted tasks
- Added functionality to save the tasks in localStorage
- Added functionality to track changes as the user edits a task

### CODE REVIEW

**Review by alexpuente0 — APPROVED** [review]
Congratulations! your code looks amazing! :star2::star2::star2::star2::star2:

giphy

Extra props for:
- Having everything well organized
- KISS methodology
- Use of Javascript best practices

There is a suggested change in the comments, which is totally optional.
Keep up the good work! :heavy_check_mark:

**Comment by Trictonicmp** [comment]
Thank you for reviewing my code!

**Comment by alexpuente0** [comment]
[OPTIONAL] - You'd probably want to consider separating the Logic of your project from the Front-end.

**Comment by Trictonicmp** [comment]
> [OPTIONAL] - You'd probably want to consider separating the Logic of your project from the Front-end.

Sure I will!!

**Pull request closed without merging**
